const ADD_CURRENCY = "ADD_CURRENCY"
const ADD_CURRENCY_HISTORY = "ADD_CURRENCY_HISTORY"
const CHANGE_CURRENCY_HISTORY = "CHANGE_CURRENCY_HISTORY"

export {ADD_CURRENCY,ADD_CURRENCY_HISTORY ,CHANGE_CURRENCY_HISTORY}